### ISSUE TITLE
Where is the Chargeprice Server repository?

### ISSUE THREAD

**Issue by johan12345** [hoenic07/charge-compare-client#12]
In the main README file, there is a link to
https://github.com/hoenic07/chargeprice
for the repository of the chargeprice web service. I wanted to take a look, but this link just leads to a 404 error. Was the repository deleted?

**Comment by hoenic07** [comment]
The code for the Backend service is private now, sorry.
If you want to have a look at the API Documentation, check this out: https://github.com/hoenic07/chargeprice-api-docs

**Comment by johan12345** [comment]
Thanks! I will take a look at the API docs, but maybe an easier first integration would be to just link to the Chargeprice website. Did you have some tome to look at my PR https://github.com/hoenic07/chargeprice-client/pull/14?
